apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardai-deployment
  labels:
    app: guardai
spec:
  replicas: 12       # specify number of replicated Pods
  selector:
    matchLabels:
      app: guardai

  template:
    metadata:
      labels:
        app: guardai

    spec:
      containers:
      - name: guardai-container
        image: paulcccccch/trustworthy-ai:latest
        ports:
        - containerPort: 8300
        envFrom:
        - configMapRef:
            name: guardai-config
        resources:
          requests:
            cpu: 500m
      imagePullSecrets:
      - name: guardai-registry-key

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guardai-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guardai-deployment
  minReplicas: 12
  maxReplicas: 18
  targetCPUUtilizationPercentage: 50
